source "https://rubygems.org"

gem "bootsnap", require: false
gem "devise"
gem "httparty"
gem "importmap-rails"
gem "jbuilder"
gem "kamal", require: false
gem "pg"
gem "propshaft"
gem "puma"
gem "rails", "~> 8.1.0"
gem "solid_cable"
gem "solid_cache"
gem "solid_queue"
gem "stimulus-rails"
gem "tailwindcss-rails"
gem "tailwindcss-ruby"
gem "thruster", require: false
gem "turbo-rails"

group :development, :test do
  gem "brakeman", require: false
  gem "database_cleaner"
  gem "database_cleaner-active_record"
  gem "factory_bot_rails"
  gem "faker"
  gem "rspec-rails"
  gem "rubocop-rails-omakase", require: false
  gem "webmock"
end

group :development do
  gem "web-console"
end

group :test do
  gem "capybara"
  gem "selenium-webdriver"
  gem "shoulda-matchers"
end
